name: Deploy Docker Frontend Web
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: docker build -t saulomarchi/fibo-calculator-client-test -f ./client/Dockerfile.dev .
      - run: docker run -e CI=true saulomarchi/fibo-calculator-client-test npm run test
 
      - name: Generate deployment package
        run: zip -r fibo-calculator-deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: fibo-calculator
          environment_name: Fibocalculator-env
          existing_bucket_name: elasticbeanstalk-us-east-1-917396685926
          region: us-east-1
          version_label: ${{ github.SHA }}
          deployment_package: fibo-calculator-deploy.zip
