name: New PR Docker Frontend Web
on:
  pull_request:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: docker build -t saulomarchi/fibo-calculator-client-test -f Dockerfile.dev .
      - run: docker run -e CI=true saulomarchi/fibo-calculator-client-test npm test

